universe = vanilla
executable = condor.sh
initialdir = fileName
arguments = $(ProcId)
output =  log/$(ProcId).out
error = log/$(ProcId).err
log = log/$(ProcId).log
request_memory = 1 GB

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = {path}/DRC_generic/install/bin, {path}/DRC_generic/install/lib, {path}/DRC_generic/install/init.mac, /DRC_generic/install/run_ele.mac

queue 500
